server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

infra:
  google:
    oauth:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}

jwt:
  secret: ThisIsAVeryLongSecretKeyForJWTTokenGenerationAndValidationMinimum256Bits
  access-token-expiration: 1800000
  refresh-token-expiration: 2592000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
